LLM_PROVIDER_GEMINI="gemini"

GEMINI_MODEL_FLASH = "gemini-2.5-flash"
GEMINI_MODEL_PRO = "gemini-2.5-pro"
GEMINI_MODEL_ULTRA = "gemini-2.5-ultra"
GEMINI_MODEL_VISION = "gemini-2.5-vision"
GEMINI_API_KEY="GOOGLE_API_KEY"


LLM_PROVIDER_GROQ="groq"
GROQ_MODEL_INSTA="llama-3.1-8b-instant"
GROQ_API_KEY="GROQ_API_KEY"


LLM_PROVIDER_OPENAI="openai"
OPENAI_API_KEY="OPENAI_API_KEY"
OPENAI_MODEL_OSS="gpt-oss-20b"
OPENAI_MODEL_4O_MINI="gpt-4o-mini"

DEEPSEEK_API_KEY="DEEPSEEK_API_KEY"
DEEPSEEK_MODEL_CHAT="deepseek-chat"
DEEPSEEK_MODEL_V3_2="deepseek-v3.2"
DEEPSEEK_MODEL_V3_2_EXP="deepseek-v3.2-exp"
DEEPSEEK_API_BASE="https://api.deepseek.com"
LLM_PROVIDER_DEEPSEEK="deepseek"
DEEPSEEK_MODEL_V3_CHAT="deepseek-chat-v3.1"